print('Hello World')
print ('Hello World')
print('Hello World')
print ('Hello')
print ('Меня зовут Вася')
print('Привет,')
print ('и я умнее всех')
print('Зелёный!!!')
print ('Бляяя... Ну , Вася!...')